name: Deploy Lambda

on:
  push:
    paths:
      - 'backend/listar-agendamentos/**'
      - '.github/workflows/deploy-lambda.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Deploy Lambda
      run: |
        # Cria arquivo ZIP APENAS com o necess√°rio
        cd backend/lambda-listar-agendamentos
        zip -r lambda.zip index.mjs
        
        # Atualiza Lambda
        aws lambda update-function-code \
          --function-name lambda-listar-agendamentos \
          --zip-file fileb://lambda.zip \
          --region us-east-2